# Generated by Django 4.0.4 on 2022-05-18 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_thumbnail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='published_year',
            new_name='published_date',
        ),
    ]
