# Generated by Django 4.0.4 on 2022-05-18 09:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_rename_published_year_book_published_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='published_date',
            new_name='publication_date',
        ),
    ]
